export const currencyByRupee: Currency[] = [
    {
        name: 'DOLLAR',
        value: 0.012271428,
        flag: '🇺🇸',
        symbol: '$',
    },
    {
        name: 'EURO',
        value: 0.01125809,
        flag: '🇪🇺',
        symbol: '€',
    },
    {
        name: 'POUND',
        value: 0.0099194378,
        flag: '🇬🇧',
        symbol: '£',
    },
    {
        name: 'RUBEL',
        value: 0.85040469,
        flag: '🇷🇺',
        symbol: '₽',
    },
    {
        name: 'AUS DOLLAR',
        value: 0.01732574,
        flag: '🇦🇺',
        symbol: 'A$',
    },
    {
        name: 'CAN DOLLAR',
        value: 0.016457908,
        flag: '🇨🇦',
        symbol: 'C$',
    },
    {
        name: 'YEN',
        value: 1.5909089,
        flag: '🇯🇵',
        symbol: '¥',
    },
    {
        name: 'DINAR',
        value: 0.0037446993,
        flag: '🇰🇼',
        symbol: 'KD',
    },
    {
        name: 'BITCOIN',
        value: 0.000000543544886,
        flag: '🎰',
        symbol: '₿',
    },
    {
        name: 'SWISS FRANC',
        value: 0.011133,
        flag: '🇨🇭',
        symbol: 'CHF',
    },
    {
        name: 'SINGAPORE DOLLAR',
        value: 0.0166,
        flag: '🇸🇬',
        symbol: 'S$',
    },
    {
        name: 'CHINESE YUAN',
        value: 0.0893,
        flag: '🇨🇳',
        symbol: '¥',
    },
    {
        name: 'BRAZILIAN REAL',
        value: 0.061,
        flag: '🇧🇷',
        symbol: 'R$',
    },
    {
        name: 'SOUTH AFRICAN RAND',
        value: 0.226,
        flag: '🇿🇦',
        symbol: 'R',
    },
    {
        name: 'INDONESIAN RUPIAH',
        value: 183.33,
        flag: '🇮🇩',
        symbol: 'Rp',
    },
    {
        name: 'MEXICAN PESO',
        value: 0.22,
        flag: '🇲🇽',
        symbol: '$',
    },
    {
        name: 'SWEDISH KRONA',
        value: 0.125,
        flag: '🇸🇪',
        symbol: 'kr',
    },
    {
        name: 'NORWEGIAN KRONE',
        value: 0.127,
        flag: '🇳🇴',
        symbol: 'kr',
    },
];
